### ISSUE TITLE
Where to configure partition key in code example.

### ISSUE THREAD

**Issue by JonnewDev-blip** [MicrosoftDocs/azure-dev-docs.sv-se#1] opened 2020-03-31 21:06 UTC
When I run the example it fails with error,

Gremlin Query Execution Error: Cannot add a vertex where the partition key property has value 'null'
Seems I need to configure a partition key somewhere but I can't find where to do it or set up Cosmos Db without a partition key which is a deprecated setup?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 027365fa-060a-d121-194a-d0b7d308e49c
* Version Independent ID: 70952df9-d97e-7d22-671e-917021b78835
* Content: [Så här använder du Spring Data Gremlin Starter med Azure Cosmos DB SQL API](https://docs.microsoft.com/sv-se/azure/java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db#feedback)
* Content Source: [java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md](https://github.com/MicrosoftDocs/azure-dev-docs.sv-se/blob/live/java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by JasonWHowell** [comment] 2020-05-12 20:46
Duplicate of https://github.com/microsoftdocs/azure-dev-docs/issues/107 Let's close this one since the other one has more progress. #please-close

**Comment by bmitchell287** [comment] 2020-05-18 17:53
#please-close

**Closed** 2020-06-29 15:18 UTC
